<script setup>
import { themeColor } from "@/data/items";
const heading = "About our data";
import img1 from "@/assets/images/platform-about-1.png";
import img2 from "@/assets/images/platform-about-2.png";
import img3 from "@/assets/images/platform-about-3.png";
const packages = [
  {
    name: "Free",
    price: "0",
  },
  {
    name: "Standard",
    price: "19.99",
  },
  {
    name: "Premium",
    price: "79.99",
  },
];
</script>
<template>
  <div class="untree_co-section bg-light" id="pricing-section">
    <div class="container">
      <div class="row pricing-title">
        <div class="col-12 text-center" data-aos="fade-up" data-aos-delay="0">
          <h2 class="tools-heading text-primary">{{ heading }}</h2>
          <p class="text-primary sub-heading">We have pioneered a unique data ingestion and computation method to
            uncover the unique identity of local
            neighbourhoods, in real time.</p>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col">
          <div class="row">
            <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
              <div class="inner-container">
                <div class="img-wrapper">
                  <img :src="img1" alt="Image" class="img-fluid" />
                </div>
                <div class="div-block">
                  <h3 class="heading-1 text-primary">PLACES</h3>
                  <p class="heading-2 text-primary">
                    <strong>Point of interest and amenities data is gathered as geo-located places from mapping
                      platforms
                    </strong>
                  </p>
                  <p class="text-primary">The information gathered from these sources is crowd-sourced and includes
                    details like the place name, location, description, opening hours, and type of place. It also
                    includes ratings and reviews, check-ins and likes.
                  </p>
                  <p class="text-primary">From this we can understand the amenity mix of a location as well as how
                    important individual places are in the neighbourhood.
                  </p>
                </div>
              </div>
            </div>
            <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
              <div class="inner-container">
                <div class="img-wrapper">
                  <img :src="img2" alt="Image" class="img-fluid" />
                </div>
                <div class="div-block">
                  <h3 class="heading-1 text-primary">BEHAVIOUR</h3>
                  <p class="heading-2 text-primary">
                    <strong>Behavioural data is generated from aggregated, anonymised, mobile phone location data.
                    </strong>
                  </p>
                  <p class="text-primary">Location is one of the most accurate predictors of behaviour and a valuable
                    insight into local life. By utilising mobile phone location data generated by app 'pings', our data
                    system recognises nearly 10,000,000 mobile devices every month.</p>
                  <p class="text-primary">The results are carefully cleaned, checked and thresholded to ensure
                    representative results across Australia.</p>
                </div>
              </div>
            </div>
            <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
              <div class="inner-container">
                <div class="img-wrapper">
                  <img :src="img3" alt="Image" class="img-fluid" />
                </div>
                <div class="div-block">
                  <h3 class="heading-1 text-primary">VALUES</h3>
                  <p class="heading-2 text-primary">
                    <strong>Values data is gathered from the publicly posted 'chatter' across local neighbourhoods.
                    </strong>
                  </p>
                  <p class="text-primary">The local experiences that people choose to post about online, provides an
                    clear insight into what locals value about their lives.
                  </p>
                  <p class="text-primary">Publicly posted content is gathered from various sources to mitigate bias, and
                    classified into 80+ lifestyle categories to reveal how people love to spend time, how they
                    socialise, and the places the love to spend time.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col btn-tools">
              <a href="#" class="btn btn-primary" :style="[
                { backgroundColor: themeColor },
              ]">Get Started</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.tools-heading {
  font-size: 50px;
  font-weight: 700;
}

.sub-heading {
  font-size: 22px;
  font-weight: 700;
}

.inner-container {}

.img-wrapper img {
  border-radius: 24px;
}

.div-block {
  margin: 20px;
  text-align: center;
}

.heading-1 {
  margin: 20px 0;
}

.div-block p {
  font-size: 18px;
}

.btn-tools {
  display: flex;
  justify-content: center;
  margin: 32px;
}
</style>